import type { RefObject } from 'react';
import type { AuthSessionSummary } from '../auth/auth-session-ui';
import type { ToastKind, ToastState } from '../ui/toast';
import type { TerminalRuntime } from '../terminal/terminal-runtime';
import type { TerminalPreviewRuntime } from '../terminal/terminal-preview';
import type { ContextualMode } from '../input/contextual-keyboard-model';
import type { ConnectionInstanceSummary } from '../terminal/terminal-protocol';
import type { ConnectionInstanceLayout, InstanceMovePlacement } from '../connections/connection-instance-groups';
import type { Heartbeat } from '../status/heartbeat';
import type { ConnectionView } from './connection-view';
import type { AppPage } from './app-state';
import type { WorkspaceTool } from './workspace-tool';
import type { WorkspaceContent } from './workspace-content';
import type { FullscreenTarget } from './use-browser-fullscreen';
import type { NotificationState } from '../status/notification-service';
import type { TerminalAppearance } from '../appearance/appearance-model';
import type { FileSystemWorkspaceState } from '../filesystem/use-filesystem-workspace';
import type { useMessages } from '../messages/use-messages';
import type { Dialog } from './app-shell-overlays';
import type { AuthState } from '../auth/auth-storage';
import type { SettingsSection } from '../settings/settings-model';

export type AppShellViewProps = {
  page: AppPage;
  auth: AuthState | null;
  appearance: TerminalAppearance;
  settingsSection: SettingsSection;
  settingsFocusTarget: string | null;
  workspaceTool: WorkspaceTool;
  workspaceToolOpen: boolean;
  connectionToolButton: RefObject<HTMLButtonElement | null>;
  keyboardToolButton: RefObject<HTMLButtonElement | null>;
  filesToolButton: RefObject<HTMLButtonElement | null>;
  settingsToolButton: RefObject<HTMLButtonElement | null>;
  nativeKeyboardOpen: boolean;
  messageButtonRef: RefObject<HTMLButtonElement | null>;
  messageCenter: ReturnType<typeof useMessages>;
  connections: ConnectionInstanceSummary[];
  connectionInstanceLayout: ConnectionInstanceLayout;
  loginSessionId: string;
  view: ConnectionView;
  heartbeatState: Heartbeat | null;
  heartbeatLatency: number | null;
  currentConnection: ConnectionInstanceSummary | undefined;
  activeInstance: ConnectionInstanceSummary | null;
  currentRuntime: TerminalRuntime | null;
  activeRuntimeId: string | null;
  previewConnectionInstanceId: string | null;
  previewRuntime: TerminalPreviewRuntime | null;
  contextualMode: ContextualMode;
  search: boolean;
  executionStatus: string | null;
  toast: ToastState | null;
  dialog: Dialog;
  dialogConnection: ConnectionInstanceSummary | undefined;
  authSessions: AuthSessionSummary[];
  currentAuthSessionId: string;
  authSessionBusy: string | null;
  onSelectWorkspaceTool: (tool: WorkspaceTool) => void;
  onCollapseWorkspaceTool: () => void;
  onHelp: () => void;
  onAddConnection: () => void;
  onSelectConnection: (id: string) => void;
  onNavigateToConnection: (id: string) => void;
  onMessageTargetUnavailable: () => void;
  onMoveConnectionInstance: (id: string, groupId: string, targetId: string | null, placement: InstanceMovePlacement) => Promise<void>;
  onReorderConnectionGroup: (id: string, targetId: string, placement: InstanceMovePlacement) => Promise<void>;
  onCreateConnectionGroup: (name: string) => Promise<boolean>;
  onRenameConnectionGroup: (id: string, name: string) => Promise<boolean>;
  onDeleteConnectionGroup: (id: string) => Promise<boolean>;
  onMoveConnectionGroupMembers: (id: string) => Promise<void>;
  onPreviewStart: (id: string) => void;
  onPreviewEnd: (id: string) => void;
  onAgent: (id: string) => void;
  onOpenFileTree: (id: string) => void;
  filesystem: FileSystemWorkspaceState;
  onRename: (id: string) => void;
  onAutomaticTitle: (id: string) => void;
  onTerminate: (id: string) => void;
  onContextualModeChange: (mode: ContextualMode) => void;
  onToggleSearch: () => void;
  onCloseSearch: () => void;
  onOpenSettings: (section?: SettingsSection, focusTarget?: string | null) => void;
  onSelectSettingsSection: (section: SettingsSection) => void;
  onFocusTargetConsumed: () => void;
  onSignOut: () => void;
  onOpenAuthSessions: () => void;
  onOpenManager: () => void;
  onCreateConnection: (definitionId: string, reuseFrom?: string, tmuxEnabled?: boolean) => Promise<boolean>;
  onGenerated: (instance: ConnectionInstanceSummary) => Promise<void>;
  onSaveAppearance: (appearance: TerminalAppearance) => void;
  onSettingsDirtyChange: (dirty: boolean) => void;
  onShowToast: (message: string, kind?: ToastKind) => void;
  onRenameTitle: (id: string, title: string | null) => Promise<void>;
  onTerminateConnection: (id: string) => Promise<void>;
  onRevokeAuthSession: (id: string) => void;
  onLogoutOtherAuthSessions: () => void;
  onCloseDialog: () => void;
  onManageNotifications: (connection: ConnectionInstanceSummary) => void;
  workspaceContent: WorkspaceContent;
  onBackToTerminal: () => void;
  appShellRef: RefObject<FullscreenTarget | null>;
  fullscreenActive: boolean;
  fullscreenSupported: boolean;
  fullscreenPending: boolean;
  onToggleFullscreen: () => void;
  notificationState: NotificationState;
  onEnableNotifications: () => Promise<void>;
  onDisableNotifications: () => Promise<void>;
};
