import '@fontsource/monaspace-neon/latin-400.css';
import '@fontsource/monaspace-neon/latin-700.css';
import '@fontsource/jetbrains-mono/latin-400.css';
import '@fontsource/jetbrains-mono/latin-700.css';
import '@fontsource/source-code-pro/latin-400.css';
import '@fontsource/source-code-pro/latin-700.css';
import '@xterm/xterm/css/xterm.css';
import './styles/tokens.css';
import './styles/layout.css';
import './styles/sidebar.css';
import './styles/monitor.css';
import './styles/dialogs.css';
import './styles/terminal.css';
import './styles/responsive.css';
import './styles/connections.css';
import './styles/filesystem.css';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { AppShell } from './app/app-shell';
import { installClientDiagnostics } from './diagnostics/client-diagnostics';

installClientDiagnostics();
createRoot(document.getElementById('root')!).render(<StrictMode><AppShell /></StrictMode>);
